[package]
name = "untitled_game"
version = "0.1.0"
edition = "2024"

[dependencies]
avian2d = "0.3.0"
bevy = "0.16.0"
bevy-tnua = "0.24.0"
bevy-tnua-avian2d = "0.5.0"

[profile.dev.package."*"]
opt-level = 3
